name: 功能请求
description: 为此项目提出一个想法，比如加一个护眼模式？
title: '[Feature Request]'
labels:
  - enhancement
assignees: LyrLark
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 请确保您遵循以下声明。
      options:
        - label: 我已搜索现有的 issues，且没有其他人提出类似的功能请求。
          required: true

        - label: 我认为有 25% 以上的用户会对该功能持正面态度。
          required: true

  - type: textarea
    id: feature
    attributes:
      label: 描述该功能
      description: 用途及您需要它的原因
      placeholder: 一个清晰且简明的功能描述，以及它将增强或解决的内容。例如：我总是为[...]感到沮丧
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 附加上下文
      placeholder: 在此添加关于功能请求的其他上下文或截图。
